### ISSUE TITLE
Not able to install from hackage

### ISSUE THREAD

**Issue by lingnand** [sboosali/enumerate#1]
For some reason `cabal install enumerate` gives me this error

```
Preprocessing library enumerate-0.0.0...

sources/Data/Enumerate/Domain.hs:34:8:
    Could not find module ‘Data.CoRec’
    Perhaps you meant
      Data.Coerce (from base-4.8.2.0)
      Data.IORef (from base-4.8.2.0)
      Data.STRef (from base-4.8.2.0)
    Use -v to see a list of the files searched for.
Updating documentation index
/Users/lingnan/.cabal/share/doc/x86_64-osx-ghc-7.10.3/index.html
cabal: Error: some packages failed to install:
enumerate-0.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

But cloning the repo and manually installing works. I'm guessing here that this is due to you commenting out Data.CoRec in the cabal file. Could you try uncommenting that for the Hackage version?

**Comment by sboosali** [comment]
oh hey, didn't know there were users. `enumerate` is used in a project that
i'm working on daily, so despite the name error (of all things), this
package is indeed being actively developed :-)

i uploaded a new version, in a bit of a rush (getting my wisdom teeth
removed soon). tell me if it works. i'll clean things up and add more
tests/documentation later this week.

btw, what are you using it for?

On Thu, May 5, 2016 at 10:47 PM, Lingnan Dai notifications@github.com
wrote:

> For some reason cabal install enumerate gives me this error
> 
> Preprocessing library enumerate-0.0.0...
> 
> sources/Data/Enumerate/Domain.hs:34:8:
>     Could not find module ‘Data.CoRec’
>     Perhaps you meant
>       Data.Coerce (from base-4.8.2.0)
>       Data.IORef (from base-4.8.2.0)
>       Data.STRef (from base-4.8.2.0)
>     Use -v to see a list of the files searched for.
> Updating documentation index
> /Users/lingnan/.cabal/share/doc/x86_64-osx-ghc-7.10.3/index.html
> cabal: Error: some packages failed to install:
> enumerate-0.0.0 failed during the building phase. The exception was:
> ExitFailure 1
> 
> But cloning the repo and manually installing works. I'm guessing here that
> this is due to you commenting out Data.CoRec in the cabal file. Could you
> try uncommenting that for the Hackage version?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sboosali/enumerate/issues/1

## 

_(this message was composed with dictation: charitably interpret typos)Sam
Boosalis_

**Comment by lingnand** [comment]
Seems like cabal still couldn't see 0.1.0 after `cabal update` (although Hackage page is already showing it) - will try again some time later.

I'm using it for a game engine where I need to represent complex hierarchical Enum types, and all of which need to be able to convert to/from Int to interface with an external API. So I was actually hoping for automatic Enum derivation... But this works too (using `elemIndex` and `!!` with `enumerated`)

**Comment by sboosali** [comment]
cool

see
https://www.reddit.com/r/haskell/comments/3txy65/better_deriving_of_enum/cxah7ac
for getting an Enum from an Enumerable

i've just added some support for the above, to make it easier for the user
to write their own instances (fewer imports, less chance of typos, etc).

see the example:

https://github.com/sboosali/enumerate/blob/master/sources/Data/Enumerate/Example.hs#L71

also i think my executable stanza was wrong, so i pushed a new version.

On Fri, May 6, 2016 at 2:33 AM, Lingnan Dai notifications@github.com
wrote:

> Seems like cabal still couldn't see 0.1.0 after cabal update (although
> Hackage page is already showing it) - will try again some time later.
> 
> I'm using it for a game engine where I need to represent complex
> hierarchical Enum types, and all of which need to be able to convert
> to/from Int to interface with an external API. So I was actually hoping for
> automatic Enum derivation... But this works too (using elemIndex and !!
> with enumerated)
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/sboosali/enumerate/issues/1#issuecomment-217309776

## 

_(this message was composed with dictation: charitably interpret typos)Sam
Boosalis_

**Comment by lingnand** [comment]
Nice! For the two CAFs in the example - array_DemoBool and table_DemoBool,
are they there because GHC wouldn't be able to optimize their sharing if
they are not put there? I was under the impression that GHC should be able
to do something for polymorphic constants - at least sharing between
invocations of the same concrete type. But I might be wrong.

On Fri, 6 May 2016, 17:07 Spiros Boosalis, notifications@github.com wrote:

> cool
> 
> see
> 
> https://www.reddit.com/r/haskell/comments/3txy65/better_deriving_of_enum/cxah7ac
> for getting an Enum from an Enumerable
> 
> i've just added some support for the above, to make it easier for the user
> to write their own instances (fewer imports, less chance of typos, etc).
> 
> see the example:
> 
> https://github.com/sboosali/enumerate/blob/master/sources/Data/Enumerate/Example.hs#L71
> 
> also i think my executable stanza was wrong, so i pushed a new version.
> 
> On Fri, May 6, 2016 at 2:33 AM, Lingnan Dai notifications@github.com
> wrote:
> 
> > Seems like cabal still couldn't see 0.1.0 after cabal update (although
> > Hackage page is already showing it) - will try again some time later.
> > 
> > I'm using it for a game engine where I need to represent complex
> > hierarchical Enum types, and all of which need to be able to convert
> > to/from Int to interface with an external API. So I was actually hoping
> > for
> > automatic Enum derivation... But this works too (using elemIndex and !!
> > with enumerated)
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > https://github.com/sboosali/enumerate/issues/1#issuecomment-217309776
> 
> ## 
> 
> _(this message was composed with dictation: charitably interpret typos)Sam
> Boosalis_
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sboosali/enumerate/issues/1#issuecomment-217485897
> 
> ## 

Lingnan Dai

**Comment by sboosali** [comment]
Right. I put them there because I'm not sure if ghc will or won't, and
suspect it doesn't (even in concrete types, like CrudOp from the example).
The `enumerated` list _must_ be shared across calls; otherwise, the
functions become linear-time, when they are assumed to be constant-time.

But if we could guarantee that `enumerated` is shared, that would be useful
for much more than cleaner default methods for Enum/Bounded. (I even have
vague ideas about allocating it statically, and/or providing support for
defining Storeable instances that just store a Ptr to the single global
array of values (I think it's called "interning"?)).

conversely, if an enumerable type is so large that we would want to stream
its values (rather than having a caf waste memory and never be garbage
collected), then it really shouldn't be an instance, see the caveat for the
orphans in Data.Enumerate.Large.

I need to read more about ghc's optimizations (the relevant one seems to be
CSE), and/or look at the core. template haskell could hide this from the
user.

On Sat, May 7, 2016 at 12:51 AM, Lingnan Dai notifications@github.com
wrote:

> Nice! For the two CAFs in the example - array_DemoBool and table_DemoBool,
> are they there because GHC wouldn't be able to optimize their sharing if
> they are not put there? I was under the impression that GHC should be able
> to do something for polymorphic constants - at least sharing between
> invocations of the same concrete type. But I might be wrong.
> 
> On Fri, 6 May 2016, 17:07 Spiros Boosalis, notifications@github.com
> wrote:
> 
> > cool
> > 
> > see
> > 
> > https://www.reddit.com/r/haskell/comments/3txy65/better_deriving_of_enum/cxah7ac
> > for getting an Enum from an Enumerable
> > 
> > i've just added some support for the above, to make it easier for the
> > user
> > to write their own instances (fewer imports, less chance of typos, etc).
> > 
> > see the example:
> > 
> > https://github.com/sboosali/enumerate/blob/master/sources/Data/Enumerate/Example.hs#L71
> > 
> > also i think my executable stanza was wrong, so i pushed a new version.
> > 
> > On Fri, May 6, 2016 at 2:33 AM, Lingnan Dai notifications@github.com
> > wrote:
> > 
> > > Seems like cabal still couldn't see 0.1.0 after cabal update (although
> > > Hackage page is already showing it) - will try again some time later.
> > > 
> > > I'm using it for a game engine where I need to represent complex
> > > hierarchical Enum types, and all of which need to be able to convert
> > > to/from Int to interface with an external API. So I was actually hoping
> > > for
> > > automatic Enum derivation... But this works too (using elemIndex and !!
> > > with enumerated)
> > > 
> > > —
> > > You are receiving this because you modified the open/close state.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sboosali/enumerate/issues/1#issuecomment-217309776
> > 
> > ## 
> > 
> > _(this message was composed with dictation: charitably interpret
> > typos)Sam
> > Boosalis_
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/sboosali/enumerate/issues/1#issuecomment-217485897
> > 
> > ## 
> 
> Lingnan Dai
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/sboosali/enumerate/issues/1#issuecomment-217569062

## 

_(this message was composed with dictation: charitably interpret typos)Sam
Boosalis_

**Comment by sboosali** [comment]
links:

https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/options-optimise.html

https://hackage.haskell.org/package/intern-0.9.1.4/docs/Data-Interned.html

On Sat, May 7, 2016 at 1:48 AM, Spiros Boosalis samboosalis@gmail.com
wrote:

> Right. I put them there because I'm not sure if ghc will or won't, and
> suspect it doesn't (even in concrete types, like CrudOp from the example).
> The `enumerated` list _must_ be shared across calls; otherwise, the
> functions become linear-time, when they are assumed to be constant-time.
> 
> But if we could guarantee that `enumerated` is shared, that would be
> useful for much more than cleaner default methods for Enum/Bounded. (I even
> have vague ideas about allocating it statically, and/or providing support
> for defining Storeable instances that just store a Ptr to the single global
> array of values (I think it's called "interning"?)).
> 
> conversely, if an enumerable type is so large that we would want to stream
> its values (rather than having a caf waste memory and never be garbage
> collected), then it really shouldn't be an instance, see the caveat for the
> orphans in Data.Enumerate.Large.
> 
> I need to read more about ghc's optimizations (the relevant one seems to
> be CSE), and/or look at the core. template haskell could hide this from the
> user.
> 
> On Sat, May 7, 2016 at 12:51 AM, Lingnan Dai notifications@github.com
> wrote:
> 
> > Nice! For the two CAFs in the example - array_DemoBool and table_DemoBool,
> > are they there because GHC wouldn't be able to optimize their sharing if
> > they are not put there? I was under the impression that GHC should be able
> > to do something for polymorphic constants - at least sharing between
> > invocations of the same concrete type. But I might be wrong.
> > 
> > On Fri, 6 May 2016, 17:07 Spiros Boosalis, notifications@github.com
> > wrote:
> > 
> > > cool
> > > 
> > > see
> > > 
> > > https://www.reddit.com/r/haskell/comments/3txy65/better_deriving_of_enum/cxah7ac
> > > for getting an Enum from an Enumerable
> > > 
> > > i've just added some support for the above, to make it easier for the
> > > user
> > > to write their own instances (fewer imports, less chance of typos, etc).
> > > 
> > > see the example:
> > > 
> > > https://github.com/sboosali/enumerate/blob/master/sources/Data/Enumerate/Example.hs#L71
> > > 
> > > also i think my executable stanza was wrong, so i pushed a new version.
> > > 
> > > On Fri, May 6, 2016 at 2:33 AM, Lingnan Dai notifications@github.com
> > > wrote:
> > > 
> > > > Seems like cabal still couldn't see 0.1.0 after cabal update (although
> > > > Hackage page is already showing it) - will try again some time later.
> > > > 
> > > > I'm using it for a game engine where I need to represent complex
> > > > hierarchical Enum types, and all of which need to be able to convert
> > > > to/from Int to interface with an external API. So I was actually
> > > > hoping
> > > > for
> > > > automatic Enum derivation... But this works too (using elemIndex and
> > > > !!
> > > > with enumerated)
> > > > 
> > > > —
> > > > You are receiving this because you modified the open/close state.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/sboosali/enumerate/issues/1#issuecomment-217309776>
> > > 
> > > ## 
> > > 
> > > _(this message was composed with dictation: charitably interpret
> > > typos)Sam
> > > Boosalis_
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/sboosali/enumerate/issues/1#issuecomment-217485897
> > > 
> > > ## 
> > 
> > Lingnan Dai
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > https://github.com/sboosali/enumerate/issues/1#issuecomment-217569062
> 
> ## 
> 
> _(this message was composed with dictation: charitably interpret typos)Sam
> Boosalis_

## 

_(this message was composed with dictation: charitably interpret typos)Sam
Boosalis_

**Comment by lingnand** [comment]
I had a discussion with a few guys on #haskell the other day about this
exact issue (sharing of polymorphic constant) and we couldn't figure it out.

Don't know much about that 'Intern' thing - not sure if this much
complexity is necessary...

For a template approach - what would it look like? I guess that would
require a separate clause from the simple 'deriving (Enumerable)' one?

On Fri, 6 May 2016, 23:50 Spiros Boosalis, notifications@github.com wrote:

> links:
> 
> https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/options-optimise.html
> 
> https://hackage.haskell.org/package/intern-0.9.1.4/docs/Data-Interned.html
> 
> On Sat, May 7, 2016 at 1:48 AM, Spiros Boosalis samboosalis@gmail.com
> wrote:
> 
> > Right. I put them there because I'm not sure if ghc will or won't, and
> > suspect it doesn't (even in concrete types, like CrudOp from the
> > example).
> > The `enumerated` list _must_ be shared across calls; otherwise, the
> > functions become linear-time, when they are assumed to be constant-time.
> > 
> > But if we could guarantee that `enumerated` is shared, that would be
> > useful for much more than cleaner default methods for Enum/Bounded. (I
> > even
> > have vague ideas about allocating it statically, and/or providing support
> > for defining Storeable instances that just store a Ptr to the single
> > global
> > array of values (I think it's called "interning"?)).
> > 
> > conversely, if an enumerable type is so large that we would want to
> > stream
> > its values (rather than having a caf waste memory and never be garbage
> > collected), then it really shouldn't be an instance, see the caveat for
> > the
> > orphans in Data.Enumerate.Large.
> > 
> > I need to read more about ghc's optimizations (the relevant one seems to
> > be CSE), and/or look at the core. template haskell could hide this from
> > the
> > user.
> > 
> > On Sat, May 7, 2016 at 12:51 AM, Lingnan Dai notifications@github.com
> > wrote:
> > 
> > > Nice! For the two CAFs in the example - array_DemoBool and
> > > table_DemoBool,
> > > are they there because GHC wouldn't be able to optimize their sharing if
> > > they are not put there? I was under the impression that GHC should be
> > > able
> > > to do something for polymorphic constants - at least sharing between
> > > invocations of the same concrete type. But I might be wrong.
> > > 
> > > On Fri, 6 May 2016, 17:07 Spiros Boosalis, notifications@github.com
> > > wrote:
> > > 
> > > > cool
> > > > 
> > > > see
> > > 
> > > https://www.reddit.com/r/haskell/comments/3txy65/better_deriving_of_enum/cxah7ac
> > > 
> > > > for getting an Enum from an Enumerable
> > > > 
> > > > i've just added some support for the above, to make it easier for the
> > > > user
> > > > to write their own instances (fewer imports, less chance of typos,
> > > > etc).
> > > > 
> > > > see the example:
> > > 
> > > https://github.com/sboosali/enumerate/blob/master/sources/Data/Enumerate/Example.hs#L71
> > > 
> > > > also i think my executable stanza was wrong, so i pushed a new
> > > > version.
> > > > 
> > > > On Fri, May 6, 2016 at 2:33 AM, Lingnan Dai <notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > Seems like cabal still couldn't see 0.1.0 after cabal update
> > > > > (although
> > > > > Hackage page is already showing it) - will try again some time
> > > > > later.
> > > > > 
> > > > > I'm using it for a game engine where I need to represent complex
> > > > > hierarchical Enum types, and all of which need to be able to convert
> > > > > to/from Int to interface with an external API. So I was actually
> > > > > hoping
> > > > > for
> > > > > automatic Enum derivation... But this works too (using elemIndex and
> > > > > !!
> > > > > with enumerated)
> > > > > 
> > > > > —
> > > > > You are receiving this because you modified the open/close state.
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > > https://github.com/sboosali/enumerate/issues/1#issuecomment-217309776>
> > > > 
> > > > ## 
> > > > 
> > > > _(this message was composed with dictation: charitably interpret
> > > > typos)Sam
> > > > Boosalis_
> > > > 
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/sboosali/enumerate/issues/1#issuecomment-217485897>
> > > > 
> > > > ## 
> > > 
> > > Lingnan Dai
> > > 
> > > —
> > > You are receiving this because you modified the open/close state.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/sboosali/enumerate/issues/1#issuecomment-217569062
> > 
> > ## 
> > 
> > _(this message was composed with dictation: charitably interpret
> > typos)Sam
> > Boosalis_
> 
> ## 
> 
> _(this message was composed with dictation: charitably interpret typos)Sam
> Boosalis_
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sboosali/enumerate/issues/1#issuecomment-217582129
> 
> ## 

Lingnan Dai

**Comment by sboosali** [comment]
you still generically derive Enumerable, and then TH derives the Enum and Bounded for you, if you choose.

**Comment by lingnand** [comment]
Yeah - I mean for the user, it would then involve two separate clauses

```
data MyData = .... deriving (Eq, Ord, Generic, Enumerable, ..)

makeEnum ''MyData
```

Instead of

```
data MyData = .... deriving (Eq, Ord, Generic, Enumerable, Enum, ..)
```

I'm probably asking for too much to be lazy though :P To be honest your
convenience functions already work great.

On Sat, 7 May 2016, 00:34 Spiros Boosalis, notifications@github.com wrote:

> you still generically derive Enumerable, and then TH derives the Enum and
> Bounded for you, if you choose.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sboosali/enumerate/issues/1#issuecomment-217587495
> 
> ## 

Lingnan Dai

**Comment by sboosali** [comment]
That would be ideal :)

But (a) deriving Enum is built-in (it doesn't use Generics, it just splices in some code) and (b) even if it did, it would need `DefaultSignature`s on its methods, which then call my generic methods. Which won't happen, since it's part of the Haskell standard.

**Comment by sboosali** [comment]
(Also, can you link me to #haskell transcripts where you discussed the
sharing issue?)

On Sat, May 7, 2016 at 2:41 AM, Lingnan Dai notifications@github.com
wrote:

> Yeah - I mean for the user, it would then involve two separate clauses
> 
> ```
> data MyData = .... deriving (Eq, Ord, Generic, Enumerable, ..)
> 
> makeEnum ''MyData
> ```
> 
> Instead of
> 
> ```
> data MyData = .... deriving (Eq, Ord, Generic, Enumerable, Enum, ..)
> ```
> 
> I'm probably asking for too much to be lazy though :P To be honest your
> convenience functions already work great.
> 
> On Sat, 7 May 2016, 00:34 Spiros Boosalis, notifications@github.com
> wrote:
> 
> > you still generically derive Enumerable, and then TH derives the Enum and
> > Bounded for you, if you choose.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/sboosali/enumerate/issues/1#issuecomment-217587495
> > 
> > ## 
> 
> Lingnan Dai
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/sboosali/enumerate/issues/1#issuecomment-217588234

## 

_(this message was composed with dictation: charitably interpret typos)Sam
Boosalis_
